### PR TITLE
added support for persistent dbs

### PR DESCRIPTION
**Pull request by pbair-modcloth**

### CODE REVIEW

**Comment by meatballhat** [comment]
why closed? :confused:

**Comment by skingry** [comment]
I see what you're trying to do here... the code looked good, but are you
going to do this by just copying a current backup into a safe place and
then restoring/refreshing from that at-will?

**Comment by meatballhat** [comment]
Update from separate chat conversation:  Symlinking MySQL databases makes MySQL very unhappy, which is why the original PR was closed.

**Comment by pbair-modcloth** [comment]
Sorry, didn't see the comment thread here. Had some issues when I tried to do this. Not sure if it was due to the actual symlinking of the database or if I screwed something up when I tried to move the database from one directory to another. At any rate I was getting file read errors when I tried to query the symlinked db.

I'm going to test this some more this week, to see if the symlinking was the issue or something else I did. It seems like symlinking _should_ work based on what I read in a few different places.

**Pull request closed without merging**
