### PR TITLE
work in progress mysql 5.6 recipe updates

### PR DESCRIPTION
**Pull request by alexschlessinger**
work in progress, do not merge yet, and...
DO NOT UPLOAD TO ORGS

### CODE REVIEW

**Comment by skingry** [comment]
np9k2zh

**Comment by rafecolton** [comment]
LGTM, let me know when it's ready to merge.

**Comment by meatballhat** [comment]
Let it be known that I'm **REEEEALLY** happy @skingry still gets notifications for this repo.

**Comment by meatballhat** [comment]
BURRRN

**Comment by skingry** [comment]
LOL

**Pull request closed without merging**
